version: '3.8'

services:
  db:
    container_name: app_db
    image: postgres:14
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: app_worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/appdb
    volumes:
      - ./common:/app/common
    working_dir: /app/
    command: ["python", "-m", "src.app"]

  web:
    container_name: app_web
    build:
      context: ./website
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/appdb
    ports:
      - "5000:5000"
    volumes:
      - ./common:/website/common
      - ./website:/website
    working_dir: /website
    command: python app.py

volumes:
  postgres-data: